apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos-raw-sound-to-spectogram
  namespace: united-manufacturing-hub
  labels:
    app: benthos-raw-sound-to-spectogram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benthos-raw-sound-to-spectogram
  template:
    metadata:
      labels:
        app: benthos-raw-sound-to-spectogram
    spec:
      containers:
        - name: benthos-raw-sound-to-spectogram
          image: "unitedmanufacturinghub/raw-sound-to-spectogram"
          imagePullPolicy: Always
