apiVersion: v1
kind: ConfigMap
metadata:
  name: benthos-raw-sound-to-spectogram-config
  namespace: united-manufacturing-hub
  labels:
    app: benthos-raw-sound-to-spectogram
data:
  benthos.yaml: |-
    input:
      kafka:
        addresses:
          - united-manufacturing-hub-kafka:9092
        topics:
          - ia.raw.audio
        consumer_group: benthos_spectogram_input
    pipeline:
      processors:
        - subprocess: 
            name: python3
            args:
              - "-u"
              - "/app/main.py"
    output:
      kafka:
        addresses:
          - united-manufacturing-hub-kafka:9092
        topic: ia.raw.sound2
        client_id: benthos_spectogram_output
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos-raw-sound-to-spectogram
  namespace: united-manufacturing-hub
  labels:
    app: benthos-raw-sound-to-spectogram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benthos-raw-sound-to-spectogram
  template:
    metadata:
      labels:
        app: benthos-raw-sound-to-spectogram
    spec:
      containers:
        - name: benthos-raw-sound-to-spectogram
          image: "unitedmanufacturinghub/raw-sound-to-spectogram"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4195
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          volumeMounts:
            - name: config
              mountPath: "/benthos.yaml"
              subPath: "benthos.yaml"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: benthos-raw-sound-to-spectogram-config
